name: panora
# version: '3.8'

services:
  magic-link-frontend:
    build:
      dockerfile: ./apps/magic-link/Dockerfile
      context: ../
      args:
        VITE_BACKEND_DOMAIN: ${NEXT_PUBLIC_BACKEND_DOMAIN}
        VITE_WEBAPP_DOMAIN: ${NEXT_PUBLIC_WEBAPP_DOMAIN}
    restart: always
    ports:
      - 81:80
    networks:
      - backend
      - frontend
networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
